services:
  - type: web
    name: palate-pilot-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://itspancakeman:C2RMk06cKtb5YZTY@collinst.24mhinb.mongodb.net/?retryWrites=true&w=majority&appName=CollinSt
      - key: JWT_SECRET
        value: mylittlesecret
    autoDeploy: true
    routes:
      - type: redirect
        from: /
        to: /

